<?php

// Generated by Haxe 3.3.0
class api_BackUpAPI {
	public function __construct() {}
	static function convertToHaxeDateTime($s_date) {
		$t_date = null;
		$tmp = $s_date->getFullYear();
		$tmp1 = _hx_string_rec($tmp, "") . "-";
		$tmp2 = $s_date->getMonth();
		$tmp3 = _hx_string_or_null($tmp1) . _hx_string_rec(($tmp2 + 1), "") . "-";
		$tmp4 = $s_date->getDate();
		$t_date = _hx_string_or_null($tmp3) . _hx_string_rec($tmp4, "");
		return Date::fromString($t_date);
	}
	static function convertToSQLDateTime($h_date) {
		$t_date = null;
		$tmp = $h_date->getFullYear();
		$tmp1 = _hx_string_rec($tmp, "") . "-";
		$tmp2 = $h_date->getMonth();
		$tmp3 = _hx_string_or_null($tmp1) . _hx_string_rec(($tmp2 + 1), "") . "-";
		$tmp4 = $h_date->getDate();
		$t_date = _hx_string_or_null($tmp3) . _hx_string_rec($tmp4, "");
		return $t_date;
	}
	static function backupData() {
		$params = php_Web::getParams();
		$str = $params->get("token");
		$cnx = sys_db_Mysql::connect(_hx_anonymous(array("host" => "localhost", "port" => 3306, "user" => "andrewco_admin", "pass" => "Ican£tthink", "database" => "andrewco_leaderboard", "socket" => null)));
		$JSON = null;
		$arrayOfRows = new _hx_array(array());
		$data = _hx_anonymous(array("leaderboardData" => $arrayOfRows));
		if($str === "B4{01PA5Nd") {
			$req = $cnx->request("SELECT * FROM GameData");
			while(true) {
				$tmp = !$req->hasNext();
				if($tmp) {
					break;
				}
				$row = $req->next();
				$tmp1 = api_BackUpAPI::convertToHaxeDateTime($row->ts);
				$data->leaderboardData->push(_hx_anonymous(array("ID" => $row->id, "Username" => $row->username, "Country" => $row->countryA2, "Scored" => $row->scoreFor, "Conceded" => $row->scoreAgainst, "Score" => $row->scoreDifference, "TS" => $tmp1)));
				unset($tmp1,$tmp,$row);
			}
			$JSON = haxe_Json::phpJsonEncode($data, null, null);
			php_Lib::hprint($JSON);
			sys_io_File::saveContent("backup.json", $JSON);
			php_Lib::hprint("<h2><br><br>SAVED TO FILE</h2>");
		} else {
			php_Lib::hprint("<h2>Token invalid</h2>");
		}
	}
	static function restoreData() {
		$params = php_Web::getParams();
		$str = $params->get("token");
		$value = sys_io_File::getContent("backup.json");
		$json = haxe_Json::phpJsonDecode($value);
		$gameData = new db_GameData();
		{
			$_g = 0;
			while($_g < 50) {
				$i = $_g++;
				$gameData->username = _hx_array_get($json, $i)->Username;
				$gameData->countryA2 = _hx_array_get($json, $i)->Country;
				$gameData->scoreFor = _hx_array_get($json, $i)->Scored;
				$gameData->scoreAgainst = _hx_array_get($json, $i)->Conceded;
				$gameData->scoreDifference = _hx_array_get($json, $i)->scoreFor - _hx_array_get($json, $i)->scoreAgainst;
				$gameData->ts = _hx_array_get($json, $i)->ts;
				unset($i);
			}
		}
		if($str === "UHT2QfT{653OV8") {
			db_Table::connect();
			$gameData->insert();
			db_Table::disconnect();
			php_Lib::hprint("<h2>Restored the backup data</h2>");
		} else {
			php_Lib::hprint("<h2>Token invalid</h2");
		}
	}
	function __toString() { return 'api.BackUpAPI'; }
}
