<?php

// Generated by Haxe 3.3.0
class api_DisplayAPI {
	public function __construct() {}
	static function convertToHaxeDateTime($s_date) {
		$t_date = null;
		$tmp = $s_date->getFullYear();
		$tmp1 = _hx_string_rec($tmp, "") . "-";
		$tmp2 = $s_date->getMonth();
		$tmp3 = _hx_string_or_null($tmp1) . _hx_string_rec(($tmp2 + 1), "") . "-";
		$tmp4 = $s_date->getDate();
		$tmp5 = _hx_string_or_null($tmp3) . _hx_string_rec($tmp4, "") . " ";
		$tmp6 = $s_date->getHours();
		$tmp7 = _hx_string_or_null($tmp5) . _hx_string_rec($tmp6, "") . ":";
		$tmp8 = $s_date->getMinutes();
		$tmp9 = _hx_string_or_null($tmp7) . _hx_string_rec($tmp8, "") . ":";
		$tmp10 = $s_date->getSeconds();
		$t_date = _hx_string_or_null($tmp9) . _hx_string_rec($tmp10, "");
		return Date::fromString($t_date);
	}
	static function queryLeaderboard($query) {
		$cnx = sys_db_Mysql::connect(_hx_anonymous(array("host" => "localhost", "port" => 3306, "user" => "root", "pass" => "", "database" => "leaderboard", "socket" => null)));
		$req = $cnx->request($query);
		php_Lib::hprint("<body>" . "<table border=1; cellpadding=4; cellspacing=0; style=border-collapse:collapse; bordercolor=f67ffff;>" . "<tr>" . "<th style=background-color:#019e9e><font style=font-family:Verdana; color=white>RANK</font></th>" . "<th style=background-color:#019e9e><font style=font-family:Verdana; color=white>USERNAME</font></th>" . "<th style=background-color:#019e9e><font style=font-family:Verdana; color=white>COUNTRY</font></th>" . "<th style=background-color:#019e9e><font style=font-family:Verdana; color=white>SCORE</font></th>" . "<th style=background-color:#019e9e><font style=font-family:Verdana; color=white>TIMESTAMP</font></th>" . "<th style=background-color:#019e9e><font style=font-family:Verdana; color=white>ID</font></th>");
		$i = 1;
		while(true) {
			$tmp = !$req->hasNext();
			if($tmp) {
				break;
			}
			$row = $req->next();
			$tmp1 = "<tr>" . "<td style=background-color:#006666><font style=font-family:Verdana; color=white>" . _hx_string_rec($i, "") . "</font></td>" . "<td style=background-color:#006666><font style=font-family:Verdana; color=white>" . _hx_string_or_null($row->username) . "</font></td>" . "<td style=background-color:#006666><font style=font-family:Verdana; color=white>" . _hx_string_or_null($row->countryA2) . "</font></td>" . "<td style=background-color:#006666><font style=font-family:Verdana; color=white>" . _hx_string_or_null($row->scoreDifference) . "</font></td>" . "<td style=background-color:#006666><font style=font-family:Verdana; color=white>";
			$tmp2 = api_DisplayAPI::convertToHaxeDateTime($row->ts);
			$tmp3 = Std::string($tmp2);
			php_Lib::hprint(_hx_string_or_null($tmp1) . _hx_string_or_null($tmp3) . "</font></td>" . "<td style=background-color:#006666><font style=font-family:Verdana; color=white>" . _hx_string_or_null($row->id) . "</font></td>" . "</tr>");
			++$i;
			unset($tmp3,$tmp2,$tmp1,$tmp,$row);
		}
		php_Lib::hprint("</table></body>");
	}
	static function displayAll() {
		php_Lib::hprint("SELECT * FROM gamedata");
		api_DisplayAPI::queryLeaderboard("SELECT * FROM gamedata");
	}
	static function displayTop10() {
		php_Lib::hprint("SELECT * FROM gamedata ORDER by scoreDifference DESC LIMIT 10");
		api_DisplayAPI::queryLeaderboard("SELECT * FROM gamedata ORDER by scoreDifference DESC LIMIT 10");
	}
	static function displayCountry($country) {
		$query = "SELECT * FROM gamedata WHERE countryA2='" . _hx_string_or_null($country) . "' ORDER by scoreDifference DESC LIMIT 10";
		php_Lib::hprint($query);
		api_DisplayAPI::queryLeaderboard($query);
	}
	static function displayYear($year) {
		$query = "SELECT * FROM gamedata WHERE ts LIKE '" . _hx_string_or_null($year) . "-%' ORDER by scoreDifference DESC LIMIT 10";
		php_Lib::hprint($query);
		api_DisplayAPI::queryLeaderboard($query);
	}
	static function displayMonth($month) {
		$query = "SELECT * FROM gamedata WHERE ts LIKE '%-" . _hx_string_or_null($month) . "-%' ORDER by scoreDifference DESC LIMIT 10";
		php_Lib::hprint($query);
		api_DisplayAPI::queryLeaderboard($query);
	}
	static function displayWeek() {
		$dateNow = Date::now();
		$dateNow->getDate();
		$dateNow->getDate();
		$dateNow->getDate();
		$dateNow->getDate();
		$dateNow->getDate();
		$dateNow->getDate();
		$tmp = $dateNow->getDate();
		$query = "SELECT * FROM gamedata WHERE ts LIKE '%-" . _hx_string_rec(($tmp - 1), "") . "%' ORDER by scoreDifference DESC LIMIT 10";
		php_Lib::hprint($query);
		api_DisplayAPI::queryLeaderboard($query);
	}
	static function displayDay($day) {
		$query = "SELECT * FROM gamedata WHERE ts LIKE '%-" . _hx_string_or_null($day) . "%' ORDER by scoreDifference DESC LIMIT 10";
		php_Lib::hprint($query);
		api_DisplayAPI::queryLeaderboard($query);
	}
	function __toString() { return 'api.DisplayAPI'; }
}
