<?php

// Generated by Haxe 3.3.0
class api_RemoveDataAPI {
	public function __construct() {}
	static function deleteData($id) {
		$params = php_Web::getParams();
		$jsonStringData = $params->get("query");
		$jsonObj = haxe_Json::phpJsonDecode($jsonStringData);
		$cnx = sys_db_Mysql::connect(_hx_anonymous(array("host" => "localhost", "port" => 3306, "user" => "andrewco_admin", "pass" => "Ican£tthink", "database" => "andrewco_leaderboard", "socket" => null)));
		if($jsonObj->token === "[T0'f7`83WYOtA,") {
			$cnx->request($jsonObj->query);
			php_Lib::hprint("<h2>Query: " . _hx_string_or_null($jsonObj->query) . "<br>Deleted data</h2>");
		} else {
			php_Lib::hprint("<h2>Token invalid</h2");
		}
	}
	function __toString() { return 'api.RemoveDataAPI'; }
}
