<?php

// Generated by Haxe 3.3.0
class Main {
	public function __construct(){}
	static function main() {
		Main::routing();
	}
	static function routing() {
		$tmp = php_Web::getURI();
		$tmp1 = php_Web::getParams();
		$d = new haxe_web_Dispatch($tmp, $tmp1);
		$len = $d->parts->length;
		$userInput = php_Web::getParams();
		$userInputString = null;
		$tmp2 = $d->parts[$len - 1];
		if($tmp2 === "createTable") {
			db_Table::connect();
			db_Table::createTable();
			db_Table::disconnect();
		} else {
			$tmp3 = $d->parts[$len - 1];
			if($tmp3 === "addData") {
				_hx_deref(new api_GameDataAPI())->addData();
			} else {
				$tmp4 = $d->parts[$len - 1];
				if($tmp4 === "displayAll") {
					api_DisplayAPI::displayAll();
				} else {
					$tmp5 = $d->parts[$len - 1];
					if($tmp5 === "displayTop10") {
						api_DisplayAPI::displayTop10();
					} else {
						$tmp6 = $d->parts[$len - 1];
						if($tmp6 === "displayCountry") {
							$userInputString = $userInput->get("country");
							api_DisplayAPI::displayCountry($userInputString);
						} else {
							$tmp7 = $d->parts[$len - 1];
							if($tmp7 === "displayYear") {
								$userInputString = $userInput->get("year");
								api_DisplayAPI::displayYear($userInputString);
							} else {
								$tmp8 = $d->parts[$len - 1];
								if($tmp8 === "displayMonth") {
									$userInputString = $userInput->get("month");
									api_DisplayAPI::displayMonth($userInputString);
								} else {
									$tmp9 = $d->parts[$len - 1];
									if($tmp9 === "displayWeek") {
										api_DisplayAPI::displayWeek();
									} else {
										$tmp10 = $d->parts[$len - 1];
										if($tmp10 === "displayDay") {
											$userInputString = $userInput->get("day");
											api_DisplayAPI::displayDay($userInputString);
										} else {
											php_Lib::hprint("<h2>You requested something else</h2>");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	function __toString() { return 'Main'; }
}
