<?php

// Generated by Haxe 3.3.0
class Main {
	public function __construct(){}
	static function main() {
		Main::routing();
	}
	static function routing() {
		$tmp = php_Web::getURI();
		$tmp1 = php_Web::getParams();
		$d = new haxe_web_Dispatch($tmp, $tmp1);
		$len = $d->parts->length;
		$userInput = php_Web::getParams();
		$userInputString = null;
		$userInputString1 = null;
		$userInputString2 = null;
		$tmp2 = $d->parts[$len - 1];
		if($tmp2 === "createTable") {
			db_Table::connect();
			db_Table::createTable();
			db_Table::disconnect();
		} else {
			$tmp3 = $d->parts[$len - 1];
			if($tmp3 === "parseData") {
				_hx_deref(new api_AddDataAPI())->parseData();
			} else {
				$tmp4 = $d->parts[$len - 1];
				if($tmp4 === "displayAll") {
					api_DisplayAPI::displayAll();
				} else {
					$tmp5 = $d->parts[$len - 1];
					if($tmp5 === "displayTop10") {
						api_DisplayAPI::displayTop10();
					} else {
						$tmp6 = $d->parts[$len - 1];
						if($tmp6 === "displayCountry") {
							$userInputString = $userInput->get("country");
							api_DisplayAPI::displayCountry($userInputString);
						} else {
							$tmp7 = $d->parts[$len - 1];
							if($tmp7 === "displayYear") {
								api_DisplayAPI::displayYear();
							} else {
								$tmp8 = $d->parts[$len - 1];
								if($tmp8 === "displayYearAll") {
									api_DisplayAPI::displayYearAll();
								} else {
									$tmp9 = $d->parts[$len - 1];
									if($tmp9 === "displayMonth") {
										api_DisplayAPI::displayMonth();
									} else {
										$tmp10 = $d->parts[$len - 1];
										if($tmp10 === "displayMonthAll") {
											api_DisplayAPI::displayMonthAll();
										} else {
											$tmp11 = $d->parts[$len - 1];
											if($tmp11 === "displayWeek") {
												api_DisplayAPI::displayWeek();
											} else {
												$tmp12 = $d->parts[$len - 1];
												if($tmp12 === "displayWeekAll") {
													api_DisplayAPI::displayWeekAll();
												} else {
													$tmp13 = $d->parts[$len - 1];
													if($tmp13 === "displayDay") {
														api_DisplayAPI::displayDay();
													} else {
														$tmp14 = $d->parts[$len - 1];
														if($tmp14 === "displayDayAll") {
															api_DisplayAPI::displayDayAll();
														} else {
															$tmp15 = $d->parts[$len - 1];
															if($tmp15 === "returnAll") {
																api_ReturnAPI::returnAll();
															} else {
																$tmp16 = $d->parts[$len - 1];
																if($tmp16 === "returnTop10") {
																	api_ReturnAPI::returnTop10();
																} else {
																	$tmp17 = $d->parts[$len - 1];
																	if($tmp17 === "returnCountry") {
																		$userInputString = $userInput->get("country");
																		api_ReturnAPI::returnCountry($userInputString);
																	} else {
																		$tmp18 = $d->parts[$len - 1];
																		if($tmp18 === "returnYear") {
																			$userInputString = $userInput->get("year");
																			api_ReturnAPI::returnYear($userInputString);
																		} else {
																			$tmp19 = $d->parts[$len - 1];
																			if($tmp19 === "returnMonth") {
																				$userInputString = $userInput->get("year");
																				$userInputString1 = $userInput->get("month");
																				api_ReturnAPI::returnMonth($userInputString, $userInputString1);
																			} else {
																				$tmp20 = $d->parts[$len - 1];
																				if($tmp20 === "returnWeek") {
																					api_ReturnAPI::returnWeek();
																				} else {
																					$tmp21 = $d->parts[$len - 1];
																					if($tmp21 === "returnDay") {
																						$userInputString = $userInput->get("year");
																						$userInputString1 = $userInput->get("month");
																						$userInputString2 = $userInput->get("day");
																						api_ReturnAPI::returnDay($userInputString, $userInputString1, $userInputString2);
																					} else {
																						$tmp22 = $d->parts[$len - 1];
																						if($tmp22 === "returnUsername") {
																							$userInputString = $userInput->get("username");
																							api_ReturnAPI::returnUsername($userInputString);
																						} else {
																							$tmp23 = $d->parts[$len - 1];
																							if($tmp23 === "removeData") {
																								$userInputString = $userInput->get("query");
																								api_RemoveDataAPI::deleteData($userInputString);
																							} else {
																								$tmp24 = $d->parts[$len - 1];
																								if($tmp24 === "backupData") {
																									api_BackUpAPI::backupData();
																								} else {
																									$tmp25 = $d->parts[$len - 1];
																									if($tmp25 === "restoreData") {
																										api_BackUpAPI::restoreData();
																									} else {
																										php_Lib::hprint("<h2>You requested something else</h2>");
																									}
																								}
																							}
																						}
																					}
																				}
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	function __toString() { return 'Main'; }
}
