<?php

// Generated by Haxe 3.3.0
class Main {
	public function __construct(){}
	static function main() {
		Main::routing();
	}
	static function routing() {
		$tmp = php_Web::getURI();
		$tmp1 = php_Web::getParams();
		$d = new haxe_web_Dispatch($tmp, $tmp1);
		$len = $d->parts->length;
		$tmp2 = $d->parts[$len - 1];
		if($tmp2 === "createTable") {
			db_Table::connect();
			db_Table::createTable();
			db_Table::disconnect();
		} else {
			$tmp3 = $d->parts[$len - 1];
			if($tmp3 === "addData") {
				_hx_deref(new api_GameDataAPI())->addData();
			} else {
				$tmp4 = $d->parts[$len - 1];
				if($tmp4 === "test") {
					php_Lib::hprint("<h2>Testing connection</h2>");
				} else {
					$tmp5 = $d->parts[$len - 1];
					if($tmp5 === "displayLeaderboard") {
						db_Table::displayLeaderboard();
					} else {
						php_Lib::hprint("<h2>You requested something else</h2>");
					}
				}
			}
		}
	}
	function __toString() { return 'Main'; }
}
