<?php

// Generated by Haxe 3.3.0
class api_GameDataAPI {
	public function __construct() {}
	public function addData() {
		$value = sys_io_File::getContent("C:\\University\\301CR - Advanced Games Programming\\Assignment 2\\Leaderboard\\Leaderboard\\src\\gameData.json");
		$json = haxe_Json::phpJsonDecode($value);
		$gameData = new db_GameData();
		$gameData->username = $json->Username;
		$gameData->countryA2 = $json->Country;
		$gameData->scoreFor = $json->Scored;
		$gameData->scoreAgainst = $json->Conceeded;
		$gameData->scoreDifference = $gameData->scoreFor - $gameData->scoreAgainst;
		db_Tables::connect();
		$gameData->insert();
		db_Tables::disconnect();
		php_Lib::hprint("<h2>Added data</h2>");
	}
	function __toString() { return 'api.GameDataAPI'; }
}
