<?php

// Generated by Haxe 3.3.0
class db_Tables {
	public function __construct(){}
	static function connect() {
		$cnx = sys_db_Mysql::connect(_hx_anonymous(array("host" => "localhost", "port" => 3306, "user" => "root", "pass" => "", "database" => "leaderboard", "socket" => null)));
		sys_db_Manager::set_cnx($cnx);
		sys_db_Manager::initialize();
	}
	static function disconnect() {
		sys_db_Manager::cleanup();
		sys_db_Manager::$cnx->close();
	}
	static function createTables() {
		$tmp = !sys_db_TableCreate::exists(db_GameData::$manager);
		if($tmp) {
			sys_db_TableCreate::create(db_GameData::$manager, null);
		}
		php_Lib::hprint("<h2>Table created</h2>");
	}
	static function displayLeaderboard() {
		$cnx = sys_db_Mysql::connect(_hx_anonymous(array("host" => "localhost", "port" => 3306, "user" => "root", "pass" => "", "database" => "leaderboard", "socket" => null)));
		$req = $cnx->request("SELECT * FROM gamedata ORDER by scoreDifference DESC LIMIT 10");
		while(true) {
			$tmp = !$req->hasNext();
			if($tmp) {
				break;
			}
			$row = $req->next();
			php_Lib::hprint(" || Username: " . _hx_string_or_null($row->username) . " || Country: " . _hx_string_or_null($row->countryA2) . " || Score: " . _hx_string_or_null($row->scoreDifference) . "<br>");
			unset($tmp,$row);
		}
	}
	function __toString() { return 'db.Tables'; }
}
